import express from 'express';
import { authenticationMiddleware } from '../auth/authentication.Middleware.js';
import { asyncControllerHandler } from '../utils/async.handler.js';
import { validator } from '../auth/auth.validation.js';
import { walkinSchema } from '../auth/auth.validation.js';
import { authorize } from '../auth/authorization.middleware.js';
import { getAllPendingAppointmentsAdminController } from './admin.controllers.js';
import { markAsDoneAppointmentController } from './admin.controllers.js';
import { cancelAppointmentADMINController } from './admin.controllers.js';
import { getALlCompletedAppointmentsController } from './admin.controllers.js';
import { viewCancelledAppointmentsController } from './admin.controllers.js';
import { viewAdminNotificationsController } from './admin.controllers.js';
import { addWalkinController } from './admin.controllers.js';
import { dashboardController } from './admin.controllers.js';
export const adminRoutes = express.Router();
adminRoutes.get('/appointments/pending', authenticationMiddleware, authorize("admin"), asyncControllerHandler(getAllPendingAppointmentsAdminController));
adminRoutes.patch('/appointments/pending', authenticationMiddleware, authorize("admin"), asyncControllerHandler(markAsDoneAppointmentController));
adminRoutes.patch('/appointments/pending/cancel', authenticationMiddleware, authorize("admin"), asyncControllerHandler(cancelAppointmentADMINController));
adminRoutes.get('/appointments/completed', authenticationMiddleware, authorize("admin"), asyncControllerHandler(getALlCompletedAppointmentsController));
adminRoutes.get('/appointments/cancelled', authenticationMiddleware, authorize("admin"), asyncControllerHandler(viewCancelledAppointmentsController));
adminRoutes.get('/notifications', authenticationMiddleware, authorize("admin"), asyncControllerHandler(viewAdminNotificationsController));
adminRoutes.post('/appointments', authenticationMiddleware, authorize("admin"), validator(walkinSchema), asyncControllerHandler(addWalkinController));
adminRoutes.get('/dashboard', authenticationMiddleware, authorize("admin"), asyncControllerHandler(dashboardController));
